server:
  port: 8081

mongock:
  transaction-enabled: false

spring:
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB


  data:
    mongodb:
      uri: mongodb://localhost:27017/abv